name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  push

jobs:
  Explore-GitHub-Actions:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}           
          touch Dev_commits
          git config --global user.email "yugaa22@gmail.com"
          git config --global user.name "yugaa22"
          git log -1 | grep commit | awk '{print $2}'  >> Dev_commits
          git add .
          git commit -m "Developper_commits"
          git push
      - run: echo "🍏 This job's status is ${{ job.status }}."
